feat: add infinity scroll of booksList
SergeiKuznetsov9/library.cleverland pull request #1
Opened 2023-06-19 12:25 UTC by SergeiKuznetsov9

2023-06-21 07:46 UTC, Gaurrus requested changes

2023-06-21 07:46 UTC, Gaurrus commented on src/components/content/content.tsx
> +                `?pagination[page]=${paginationPage}&pagination[pageSize]=${BOOKS_LIST.pageSize}${filtersPayload}`,
Это часть строки URL? или что это? старнный payload

2023-06-21 07:54 UTC, SergeiKuznetsov9 commented on src/components/content/content.tsx
> +                `?pagination[page]=${paginationPage}&pagination[pageSize]=${BOOKS_LIST.pageSize}${filtersPayload}`,
Да, URL с параметрами

2023-06-22 08:36 UTC, Gaurrus approved these changes

2023-06-22 14:32 UTC, merged