Filters
SergeiKuznetsov9/library.cleverland pull request #2
Opened 2023-07-04 19:44 UTC by SergeiKuznetsov9

Добавлены сортировки по заданным критериям, фильтр забронированных книг, а также поиск

2023-07-05 07:14 UTC, Gaurrus requested changes

2023-07-05 07:14 UTC, Gaurrus commented on src/components/content/content.tsx
> +        );
выноси в отдельный файл utils или helpers

2023-07-05 07:14 UTC, Gaurrus commented on src/components/menu/menu.tsx
> +    }, [isSearchExpanded, isFilteringExpanded]);
давай вот эти вещи через css реализуем, медиазапросами

2023-07-05 07:14 UTC, Gaurrus commented on src/components/sorting-chips/chips/chips.module.scss
> +    font-family: Montserrat;
а он глобальго у родительских элеменотв другой? или в глобальном файле css не прописано inherit?

2023-07-05 08:45 UTC, Gaurrus commented on src/components/content/content.tsx
>  import { useParams } from 'react-router-dom';
![image](https://github.com/SergeiKuznetsov9/library.cleverland/assets/85307211/8a68fa4c-2e48-428b-8f96-889d000eb323)
если включить "Скрыть бронь" и зпбронировать книгу - сразу не фильтрует

2023-07-05 08:45 UTC, Gaurrus commented on src/components/content/content.tsx
>  import classNames from 'classnames';
![image](https://github.com/SergeiKuznetsov9/library.cleverland/assets/85307211/b6754f29-7c90-4ad5-89a2-c208dd21158c)
не сортирует в списке

2023-07-05 08:45 UTC, Gaurrus commented on src/components/content/content.tsx
![image](https://github.com/SergeiKuznetsov9/library.cleverland/assets/85307211/1c8c4357-7889-4025-8675-1463d94b21ae)
![image](https://github.com/SergeiKuznetsov9/library.cleverland/assets/85307211/bd6a4647-f829-4485-8d29-2ffce65a56c2)
поиск не работает, и надо не по нажатию Enter  а при наборе чтобы сразу фильтровал

2023-07-05 19:22 UTC, SergeiKuznetsov9 commented on src/components/content/content.tsx
Да, поиск по автору не сделал, только по названию. Я правильно понимаю, что поиск делаем на бэке, но ставим задержку для направления запроса, чтобы запросы сразу же при первом инпуте не улетали?

2023-07-05 19:39 UTC, SergeiKuznetsov9 commented on src/components/menu/menu.tsx
> +    }, [isSearchExpanded, isFilteringExpanded]);
Тут вопрос. Суть такая: по дизайну инпут для поиска на узком экране имеет два состояния: состояния раскрытого инпута и закрытого. Причем повторюсь, только при узкой ширине. Когда инпут раскрыт, все прочие элементы исчезают. Соответственно для того, чтобы переключать эти состояния в коде используется useState, к значению которого привязано то или иное состояние инпута. На сколько я понимаю, изменить значение стейта при помощи медиазапроса не получится, поэтому и добавлен этот листенер. В противном случае, если мы с узкого экрана при раскрытом инпуте, перейдем на широкий экран, то скрытые из-за значения в стэйте элементы, на экране не появятся. То что мне в голову приходит без использования этого листенера - так это два варианта верстки - один для узкого экрана, второй для широкого. Как тут лучше всего все это сделать?

2023-07-05 19:40 UTC, SergeiKuznetsov9 commented on src/components/content/content.tsx
> +        );
Тут понятно

2023-07-05 19:41 UTC, SergeiKuznetsov9 commented on src/components/sorting-chips/chips/chips.module.scss
> +    font-family: Montserrat;
тут разберусь

2023-07-05 19:45 UTC, SergeiKuznetsov9 commented on src/components/content/content.tsx
>  import { useParams } from 'react-router-dom';
Тут вопрос, нужна подсказка. Суть такая: если мы на первой странице - проблем нет, перенаправили запрос и все. А как быть если мы проскролили к примеру до пятой страницы и забронировали книгу. Можно конечно же все обнулить и получить первую страницу, но будет ли это красиво. А если нет, то как? Если просто из стора забронированную книгу выкинуть - вообще очень плохо будет. Как тут лучше сделать?

2023-07-05 19:46 UTC, SergeiKuznetsov9 commented on src/components/content/content.tsx
>  import classNames from 'classnames';
Тут понятно, разберусь

2023-07-05 20:02 UTC, Gaurrus commented on src/components/menu/menu.tsx
> +    }, [isSearchExpanded, isFilteringExpanded]);
Мне кажется что что там не будет 2 верстки.  Можешь попробовать в отдельной ветке реализовать? Стейт же 1 используешь, вот вместо него триггером будут медиазапросы которые будут подкидывать нужные свойства. Раскрывать или скрывать элементы

2023-07-05 20:03 UTC, Gaurrus commented on src/components/menu/menu.tsx
> +    }, [isSearchExpanded, isFilteringExpanded]);
А если он только при узкой ширине, зачем тогда ресайз отслеживать?

2023-07-06 06:29 UTC, SergeiKuznetsov9 commented on src/components/menu/menu.tsx
> +    }, [isSearchExpanded, isFilteringExpanded]);
Ок, попробую. Еще пара вопросов в комментах ниже

2023-07-06 06:31 UTC, Gaurrus commented on src/components/content/content.tsx
>  import { useParams } from 'react-router-dom';
да, ты можешь уже полученные книги просто поменять стейт, это даже лучше, поменять одну книгу чем тянуть весь массив

2023-07-06 06:32 UTC, Gaurrus commented on src/components/content/content.tsx
сделай лучше без бэка, тут сервер тупит и выглядит ужасно когда через бэк летит)

2023-07-09 10:31 UTC, SergeiKuznetsov9 commented on src/components/content/content.tsx
>  import classNames from 'classnames';
тут дело оказалось не в списке, а в том, что сортировка по рейтингу через бэк не работает - сделал ее на фронте

2023-07-09 12:24 UTC, SergeiKuznetsov9 commented on src/components/menu/menu.tsx
> +    }, [isSearchExpanded, isFilteringExpanded]);
Сделал

2023-07-09 13:26 UTC, SergeiKuznetsov9 commented on src/components/content/content.tsx
Сделал

2023-07-11 12:40 UTC, Gaurrus approved these changes

2023-07-12 06:14 UTC, merged