Admin page users
SergeiKuznetsov9/library.cleverland pull request #6
Opened 2023-09-18 07:27 UTC by SergeiKuznetsov9

1. Фильтр, поиск и сортировка клиентов в разделе администрирования;
2. Блокировка и разблокирование пользователей в разделе администрирования;
3. Выдача и возврат книги в разделе администрирования;
4. Продление срока выдачи книги в разделе администрирования;

2023-09-18 20:25 UTC, Gaurrus requested changes

2023-09-18 20:25 UTC, Gaurrus commented on src/components/admin-components/book-card-admin/book-card-admin.tsx
> +                recipient: booking?.customerId as number,
А если customerId придет все же не число? Может лучше определить четко тип там откуда он приходит?

2023-09-18 20:25 UTC, Gaurrus commented on src/components/admin-components/clients-list-admin/clients-list-admin.tsx
> +        );
вот это дело утилитка какая-то не может выполнять?

2023-09-18 20:25 UTC, Gaurrus commented on src/components/card/card.tsx
> +                            Отменить броньrfgdrg
броньrfgdrg ?)

2023-09-18 20:25 UTC, Gaurrus commented on src/store/books/index.ts
> +            state.bookList.data = newBooksArray ?? [];
nit: я бы поставил `||` он привычнее

2023-09-18 20:25 UTC, Gaurrus commented on src/store/clients/index.ts
> +            state.clientBlock.isSuccess = true;
тут возможен кейс когда например произошла ошибка, и ты делаешь повторный запрос, при этом ошибка продолжает висеть `isError=true` это конечно может по разному влиять на UI  в зависимости от реализации, но я бы делал везде по 3 состояния и сбрасывал `isError` при новой попытке запроса

2023-09-18 20:25 UTC, Gaurrus commented on src/store/issues/sagas.ts
> +        if (payload.data.isBooked) {
старайся по возможности деструктуризировать всё вот это, что не таких сосисок не получалось

2023-09-18 20:25 UTC, Gaurrus commented on src/store/issues/sagas.ts
> +                dateHandedFrom: data.attributes.dateHandedFrom,
вот тут еслибы деструктуризировал сразу, то вместо `:` ставим `,` и впИрот
```
{
                dateHandedFrom,
                dateHandedTo,
                handed: true,
                id,
                recipientFirstName,
                recipientId,
                recipientLastName,
}
```

2023-09-18 20:25 UTC, Gaurrus commented on src/store/issues/sagas.ts
> +                recipientFirstName: payload.data.recipientFirstName as string,
и опять, а если не строка?

2023-09-18 20:25 UTC, Gaurrus commented on src/store/issues/sagas.ts
> +                recipientLastName: payload.data.recipientLastName as string,
и тут

2023-09-18 20:25 UTC, Gaurrus commented on src/store/saga.ts
тесты на утилки

2023-09-18 20:25 UTC, Gaurrus commented on src/components/navigation/navigation.tsx
> +                        dispatch(searchBookList(''));
нельзя сделать не обязательным, чтобы не передавать вот тут кучу `''` пустых строк, а сделать красивые `searchBookList()`?

2023-09-21 12:09 UTC, SergeiKuznetsov9 commented on src/store/books/index.ts
> +            state.bookList.data = newBooksArray ?? [];
А что значит nit?

2023-09-21 12:55 UTC, SergeiKuznetsov9 commented on src/store/clients/index.ts
> +            state.clientBlock.isSuccess = true;
Поправил

2023-09-21 12:59 UTC, SergeiKuznetsov9 commented on src/store/issues/sagas.ts
> +        if (payload.data.isBooked) {
поправил

2023-09-21 13:25 UTC, SergeiKuznetsov9 commented on src/store/issues/sagas.ts
> +                dateHandedFrom: data.attributes.dateHandedFrom,
Отрефакторил

2023-09-21 13:26 UTC, SergeiKuznetsov9 commented on src/store/issues/sagas.ts
> +                recipientFirstName: payload.data.recipientFirstName as string,
Поправил

2023-09-21 13:33 UTC, SergeiKuznetsov9 commented on src/store/issues/sagas.ts
> +                recipientLastName: payload.data.recipientLastName as string,
Поправил

2023-09-21 13:56 UTC, SergeiKuznetsov9 commented on src/components/navigation/navigation.tsx
> +                        dispatch(searchBookList(''));
Поправил

2023-09-21 14:12 UTC, Gaurrus approved these changes

2023-09-23 14:02 UTC, merged